main: university.quaranteen.gradcraft.GradCraftPlugin
name: GradCraft
api-version: '1.15'
version: '0.0.0-test'
description: A Plugin for QU
author: md_5
website: quaranteen.university
depend:
  - BKCommonLib
commands:
  diploma:
    description: Diploma command
    usage: /diploma