db:
  username: root
  password: asdfasdf
  server: jdbc:mysql://localhost:3306/graduation
  driver: com.mysql.jdbc.Driver
gradWorld: world
stageRegion: stage
gradTpPoint:
  x: 0
  y: 67
  z: 0
gradTpOutPoint:
  x: 3
  y: 67
  z: 8
degreeNpcPoint:
  x: 0
  y: 67
  z: 0
